import React from 'react';

function TermCondition() {
  return (
    <section className="p-8 bg-white text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Loyaltty Merchant Terms & Conditions</h1>
      <h2 className="text-2xl font-bold mb-4">MERCHANT TERMS AND CONDITIONS</h2>
      <p className="mb-4">
        These Merchant Terms and Conditions (the "Terms and Conditions") govern and are incorporated into the Loyaltty Merchant Agreement between Loyaltty and Merchant (collectively, the "Agreement"). Loyaltty, subject to the provisions of this paragraph, may amend the Terms and Conditions in its sole discretion and at any time.
      </p>
      <p className="mb-4">
        The most recent version of the Terms and Conditions (as may be amended by Loyaltty from time to time) will be available in Loyaltty's Merchant app. Merchant agrees that this notification method constitutes adequate notice to inform Merchant of any amendments to the Agreement and Merchant further agrees to be bound by any such amendments to the Agreement upon such notification.
      </p>
      <h2 className="text-2xl font-bold mb-4">Definitions</h2>
      <p className="mb-4">
        <strong>"MERCHANT OFFERING"</strong> means the goods and/or services to be provided by the Merchant, stated on the Online Deal Coupon as created by the Merchant in the Loyaltty App at values determined by Merchant.
      </p>
      <p className="mb-4">
        <strong>"MAXIMUM NUMBER OF COUPONS"</strong> means the maximum number of Coupons Loyaltty is authorized to administer the sale of on behalf of the Merchant.
      </p>
      <p className="mb-4">
        <strong>"MONTHLY MAXIMUM NUMBER OF COUPONS"</strong> means the maximum number of Coupons Loyaltty is authorized to administer the sale of on behalf of Merchant each month.
      </p>
      <p className="mb-4">
        <strong>"FULL OFFER VALUE"</strong> means the Amount Paid plus the Promotional Value.
      </p>
      <p className="mb-4">
        <strong>"AMOUNT PAID"</strong> means the amount a purchaser pays for each Coupon.
      </p>
      <p className="mb-4">
        <strong>"PROMOTIONAL VALUE"</strong> means the Full Offer Value less the Amount Paid.
      </p>
      <p className="mb-4">
        <strong>"PROMOTIONAL VALUE EXPIRATION DATE"</strong> means the date stated on the Coupon Deal when the Promotional Value expires.
      </p>
      <p className="mb-4">
        <strong>"FINE PRINT"</strong> means the conditions and restrictions concerning Deal redemption and the Merchant Offering stated on the Deal created within the Loyaltty Merchant App.
      </p>

      <h2 className="text-2xl font-bold mb-4">1. Voucher Program</h2>
      <ul className="list-disc ml-8 mb-4">
        <li className="mb-2">
        Loyaltty is authorized to promote and sell CouponsCoupon Deals on Merchant’s behalf subject to the terms of this Agreement and the “Terms of Sale” of the App. The Coupon Deal will evidence the Merchant Offering and can be redeemed by a purchaser while physically visiting the Merchant store. The purchaser may redeem the Deal with the Merchant by presenting the Coupon in paper or electronic form. Merchant is the issuer of the CouponsCoupon Deals and seller of the Merchant Offering. If there is a conflict between this Agreement and the Terms of Sale, the Agreement controls.
          </li>
          <li className="mb-2">
          Loyaltty is authorized to promote and sell Coupons on Merchant’s behalf through any platform, including its feature deal-of-the-day, affiliates, business partner network, marketplace, or referral network. The Coupons may be offered to all or part of Loyaltty’s subscriber base or its affiliate subscriber base or referral network and segmented by various variables including gender, age, location, and consumer preferences.
          </li>
          <p className="mb-4">
          The features may be offered through a variety of distribution channels, including, the Internet, the App, affiliate websites, business partner network, email, mobile applications, other types of electronic offerings and other platforms or distribution channels owned, controlled, or operated by Loyaltty, its affiliates or business partners. In addition, in connection with Loyaltty’s promotion of a Merchant Offering, Merchant authorizes Loyaltty to shorten or extend the Promotional Value Expiration Date.</p>
          <li className='mb-2'>
          For appointment-based Merchant Offerings, Loyaltty may require that Merchant provide Loyaltty with a calendar of available appointment times and allow Loyaltty purchasers to schedule appointments with the Merchant through Loyaltty and any third-party service Loyaltty may use. Loyaltty may audit Merchant response times using various methods, including but not limited to, auto-dialers, call forwarding and pre-recorded calls. If Loyaltty, in its sole discretion, determines Merchant response times or the quality of service provided to purchasers is unsatisfactory, Loyaltty may terminate the Agreement and return the Amount Paid to purchasers for unredeemed Coupon Deals.
          </li>
          <li className='mb-2'>
          Any Merchant who provides a Merchant Offering that includes massage services shall: (i) conduct social media searches for all of its employees, agents and/or independent contractors performing any massage service to ensure that they maintain a good reputation; and (ii) confirm that its employees, agents and/or independent contractors providing massage services have the required licenses and/or certifications, as well as meet other applicable state law requirements, for performing the services. Further, Merchant shall certify to Loyaltty annually that it is in compliance with (i) and (ii) above.
          </li>
          <li className='mb-2'>Merchant shall promptly notify Loyaltty any time it receives a complaint related to potentially criminal conduct, including allegations of sexual assault, allegedly engaged in by any of its employees, agents or independent contractors, regardless of whether a Loyaltty customer makes the complaint.</li>
          <li className='mb-2'>Loyaltty is authorized to promote and sell up to the Maximum Number of Coupons via its Merchant App and on dates in its discretion. If Merchant elects to offer recurring month-to-month features, then Loyaltty will promote and sell up to the Maximum Number of Coupons for the initial feature, then promote and sell up to the Monthly Maximum Number of Coupons for subsequent features. Merchant shall specify the Maximum Number of Coupons and may increase either number in its discretion.
          </li>
          <li className='mb-2'>Loyaltty reserves the continuing right to reject, revise, or discontinue any Merchant Offering, at any time and for any reason in Loyaltty’s sole discretion, and to terminate the Merchant Offering and to remove all references to the Merchant Offering and Coupon from its App and redirect or delete any URL used in connection with the Merchant Offering.</li>
          <li className='mb-2'>Merchant shall honor the Coupons for the Merchant Offering through the Promotional Value Expiration Date.</li>
          <li className='mb-2'>If the goods and services constituting the Merchant Offering and stated on the Voucher are no longer available, the Merchant must always allow the purchaser to redeem the Coupon toward any goods or services then offered by the Merchant equivalent to at least the Amount Paid.</li>
          <li className='mb-2'>Partial redemptions: If applicable, and if a purchaser redeems a Coupon for less than the Amount Paid, the Merchant is responsible for handling any unredeemed value as required by applicable law.</li>
          <li className='mb-2'>Merchant agrees that in providing the Merchant Offering, Merchant will not inflate prices or impose any additional fees, charges, conditions, or restrictions that contradict or are inconsistent with the terms stated on the Coupon, including the Fine Print. Unless disclosed in the Fine Print, Merchant further agrees not to impose different terms or a different cancellation policy than what is imposed on its non-Loyaltty customers.</li>
          <li className='mb-2'>Merchant agrees that so long as an appointment or reservation is made to redeem a Coupon, or purchaser has made an attempt to make an appointment, before the Coupon’s Promotional Value Expiration Date, the Coupon will be honored for the Full Offer Value without restriction, even though the services may be provided after the Promotional Value Expiration Date.</li>
          <li className='mb-2'>Merchant is responsible for all customer service in connection with the Merchant Offering and for supplying all goods and services stated in the Merchant Offering. Merchant is also responsible for any customer loyalty programs associated with the Merchant Offering</li>
          <li className='mb-2'>Merchant will hold the Merchant Offering for pick-up by each purchaser at the Redemption Site. The “Redemption Site” is the complete and accurate address provided by Merchant to Loyaltty where purchasers are able to redeem the Coupon to pick-up the Merchant Offering. Merchant also agrees to provide Loyaltty with the hours and dates of operation, complete with any exceptions, and a valid phone number for the Redemption Site. If any of the information related to a Redemption Site changes, Merchant agrees to notify Loyaltty immediately of such change.</li>
          <li className='mb-2'>Merchant agrees to accept returns of the Merchant Offering in compliance with applicable laws and the Fine Print. The Merchant agrees that its general return, replacement and refund policies applicable for non-Loyaltty app purchasers, will also be extended to purchasers who purchased Goods or Services by Redeeming Coupon Deals in Loyaltty App in all circumstances.</li>
          <li className='mb-2'>Merchant is responsible for compliance with all applicable laws, including the warning requirements mandated by California’s Proposition 65 (“Prop 65”).  Products containing the chemicals on this list require a disclaimer under Prop 65 (the “Prop 65 Chemicals”).  Merchant agrees to include the following disclaimer on any deal page for any product containing, or any service using a product that contains, any Prop 65 Chemical(s): “This product or service can expose you to chemical(s) including [name of one or more chemicals], which are known to the State of California to cause cancer, birth defects and/or other reproductive harm. For more information go to www.P65Warnings.ca.gov/.”</li>
          <li className='mb-2'>Merchant is responsible for providing the information for, and ensuring the accuracy of all statements on, the Merchant Loyaltty App related to the Merchant Offering.  Merchant assumes all liability for inaccuracies or misstatements regarding the Merchant Offering on the App.</li>
          <li className='mb-2'>Merchant will not seek reimbursement from any federal or state healthcare program, as defined in 42 U.S.C. § 1320a-7b, for any goods or services included in any Merchant Offering, and where such would violate any provision of 42 U.S.C. § 1320a-7b.</li>
          <li className='mb-2'>Merchant agrees that the amount represented by Merchant as the Full Offer Value of the Merchant Offering (if any) is the actual, regular value of the goods and/or services to be provided by the Merchant, complies with applicable laws and is, at a minimum, an accurate representation of the price at which Merchant has made substantial sales of the goods and/or services in the last 90 days. </li>
          <p className='mb-2'>Merchant further represents and warrants that Merchant has not inflated or increased the Full Offer Value and agrees that it will not manipulate pricing or advertised values in any way that could be perceived as unfair, deceptive, misleading, and/or outside the ordinary course of business. </p>
          <p className='mb-2'>Merchant takes full responsibility for ensuring that the Full Offer Value remains accurate and is updated whenever necessary to comply with the preceding terms and applicable laws.</p>
          
        </ul>
        <h2 className="text-2xl font-bold mb-4">2. Payment</h2>
        <ul className="list-disc ml-8 mb-4">
          <li className='mb-2'>Loyaltty is not responsible for collecting the amount paid by purchaser on any Tax applicable towards purchases while Redemption of Coupon. Any payment or refund shall be performed directly between the Merchant and the Purchasers at the Merchant Store. The Merchant is solely responsible for collecting and withholding any taxes as needed.</li>
          <li className='mb-2'>Taxes Generally. It is Merchant’s responsibility to determine what, if any, taxes apply to the payments Merchant makes or receives, and it is Merchant’s responsibility to collect, report and remit the correct tax to the appropriate tax authority.</li>
          <p className='mb-2'>Loyaltty is not responsible for determining whether taxes apply to Merchant’s transaction with either purchasers or Loyaltty, or for collecting, reporting or remitting any taxes arising from any transaction with or by Merchant and purchaser.</p>
          <p className='mb-2'>Merchant may be asked to provide Loyaltty with a valid Tax Identification Number for tax reporting purposes. Notwithstanding anything else in this Agreement, Merchant shall be, and will remain, registered for sales, use and other similar tax collection purposes in all states and localities in which Merchant is required to be so registered in connection with the Merchant Offering and pursuant to the terms and redemption of the Coupon, and shall be responsible for paying any and all sales, use or any other taxes related to the Merchant Offering or the goods and services.</p>
          <li className='mb-2'>Transaction Taxes. Merchant bears sole financial responsibility for any and all sales, use, excise, general, GST, or other similar taxes, including any interest penalties and additions related thereto, imposed on or arising from the transactions contemplated by this Agreement between Loyaltty and Merchant (“Transaction Taxes”), if any. Loyaltty shall apply the applicable Transaction Tax if any fees is remitted to Loyaltty pursuant this Agreement.</li>
          <p className='mb-2'>Loyaltty shall apply the applicable Transaction Tax if any fees is remitted to Loyaltty pursuant this Agreement.
          Transaction Taxes are calculated using the Merchant’s billing address and will be included on invoices. Tax rates are subject to change. If applied, Transaction Taxes will be calculated at the time of each payment using the rates in effect under current law.</p>
          <li className='mb-2'>Is not responsible for collecting or withholding any taxes from the purchaser.</li>
          </ul>

          <h2 className="text-2xl font-bold mb-4">3. Customer Data Restrictions</h2>
        <ul className="list-disc ml-8 mb-4">
          <li className='mb-2'>"Customer Data" means all identifiable information about purchasers generated or collected by Loyaltty or Merchant, including, but not limited to, purchasers’ name, shipping addresses, email addresses, phone numbers, purchaser preferences and tendencies, and financial transaction data.</li>
          <li className='mb-2'>Merchant shall use Customer Data only to fulfill its redemption obligations in connection with the Merchant Offering as authorized by this Agreement. Merchant expressly agrees that any Customer Data shall be used only for this purpose (including, but not limited to, the redemption of Coupons and provision of goods and services to purchasers), and not to enhance a file or list owned by Merchant, or any third party.</li>
          <p className='mb-2'>Merchant represents, warrants and covenants that it will not resell, broker or otherwise disclose any Customer Data to any third party, in whole or in part, for any purpose, unless required by applicable law. If Merchant engages any third party to facilitate its redemption obligations hereunder, Merchant shall ensure that such third party implements and complies with reasonable security measures in handling any Customer Data.</p>
          <p className='mb-2'>Merchant represents, warrants and covenants that it will not resell, broker or otherwise disclose any Customer Data to any third party, in whole or in part, for any purpose, unless required by applicable law. If Merchant engages any third party to facilitate its redemption obligations hereunder, Merchant shall ensure that such third party implements and complies with reasonable security measures in handling any Customer Data.</p>
          <li className='mb-2'>As long as Merchant uses Customer Data in compliance with applicable law and Merchant’s posted privacy policy, restrictions stated in this Agreement on Merchant’s use of Customer Data do not apply to: (i) data from any purchaser who is already a customer of Merchant before the Effective Date, if such data was provided to Merchant by such purchaser independent of this Agreement or any transaction hereunder; or (ii) data supplied by a purchaser directly to Merchant who becomes a customer of Merchant in connection with such purchaser explicitly opting in to receive communications from Merchant.</li>
          <li className='mb-2'>Merchant shall immediately notify Loyaltty if Merchant becomes aware of or suspects any unauthorized access to or use of Customer Data or any confidential information of Loyaltty, and shall cooperate with Loyaltty in the investigation of such breach and the mitigation of any damages. Merchant will bear all associated expenses incurred by Loyaltty to comply with applicable laws (including, but not limited to, any data breach laws) or arising from any unauthorized access or acquisition of Customer Data while such data is in Merchant’s reasonable possession or control. Upon termination or expiration of this Agreement, Merchant shall, as directed by Loyaltty, destroy or return to Loyaltty all the Customer Data in Merchant’s or any agent of Merchant’s possession.</li>
          </ul>

          <h2 className="text-2xl font-bold mb-4">4.Mobile Redemption Devices</h2>
          <p className='mb-2'>If Loyaltty leases or lends Merchant a tablet or mobile redemption device (“Device”), Merchant agrees to be bound by the terms of use, end user license agreements, or other provisions governing its use, unless otherwise authorized by Loyaltty in writing.</p>
          <p className='mb-2'>Unless otherwise stated in writing, Merchant shall only use the Device for transmitting redemption data to Loyaltty and processing purchaser payments and shall return a loaned Device fourteen (14) days after the Promotional Value Expiration Date, unless a new feature is planned or if requested by Loyaltty for any reason. Loyaltty reserves the right to bill Merchant for the cost of the Device, or offset any current or future payments due to Merchant under any contract between the parties if the device is not returned, or for costs related to damage or other misuse.</p>

          <h2 className="text-2xl font-bold mb-4">5. Term and Termination</h2>
          <p className='mb-2'>This Agreement will continue in effect until terminated by either party in accordance with this Section (“Term”). Loyaltty is authorized to terminate this Agreement, at any time for any reason, upon written notice to Merchant. Merchant is authorized to terminate this Agreement upon seven (7) business days prior written notice to Loyaltty. Termination of this Agreement will not in any way affect Merchant’s obligation to redeem any Coupon according to the terms of this Agreement, including the obligation to honor the Coupon for the Amount Paid after the Promotional Value Expiration Date. Provisions in this Agreement that are intended to survive termination will continue in full force and effect after the Term.</p>

          <h2 className="text-2xl font-bold mb-4">6. Compliance with Gift Card, Gift Certificate and Abandoned Property Laws</h2>
          <p className='mb-2'>Merchant agrees to comply with the Coupon terms and conditions as stated on the App, including but not limited to the “Terms of Use” of the App, and to ensure that the Coupons comply with all laws that govern Coupons, gift cards, coupons, and gift certificates, including but not limited to the United States Credit CARD Act of 2009 (if applicable) and any laws governing the imposition of expiration dates, service charges or dormancy fees and all Fine Print related to the Merchant Offering stated on the Coupon. Merchant is solely responsible for compliance with any applicable escheat or abandoned or unclaimed property laws. Upon written request from Merchant, but only when required, Loyaltty will provide Merchant with information in Loyaltty’s possession that the Merchant needs to comply with its obligations under this Agreement. Merchant agrees that, regardless of the payment terms, Merchant, and not Loyaltty, maintains any obligation for unredeemed Coupons under applicable escheat or abandoned or unclaimed property laws.</p>

          <h2 className="text-2xl font-bold mb-4">7. Marketing</h2>
          <p className='mb-2'>Loyaltty and its business partners may communicate with Merchant with regard to products, promotions, and other services that may be of interest to Merchant. This may include email or other communications. Loyaltty may also solicit Merchant’s opinion for market research purposes.</p>

          <h2 className="text-2xl font-bold mb-4">8.Intellectual Property Rights</h2>
          <ul className="list-disc ml-8 mb-4">
            <li className='mb-2'>
            Merchant grants to Loyaltty a non-exclusive, worldwide, royalty free, paid-up, perpetual, irrevocable, transferable and sub-licensable license and right to use, modify, reproduce, sublicense, publicly display, distribute, broadcast, transmit, stream, publish and publicly perform: (a) Merchant’s name, logos, trademarks, service marks, domain names, and any audiovisual content, video recordings, audio recordings, photographs, graphics, artwork, text and any other content provided, specified, recommended, directed, authorized or approved to use by Merchant (collectively, “Merchant IP”); and (b) any third party’s name, logos, trademarks, service marks, domain names, audiovisual recordings, video recordings, audio recordings, photographs, graphics, artwork, text and any other content provided, specified, recommended, directed, authorized or approved for use by Merchant (collectively, “Third Party IP”), in each case in connection with the promotion, sale/resale (as may be applicable) or distribution of the Merchant Offering in all media or formats now known or hereinafter developed (“License”). Any use of the Merchant IP or Third Party IP as contemplated in this Agreement is within Loyaltty’s sole discretion.
            </li>
            <li className='mb-2'>
              Merchant acknowledges and agrees that, as between the parties, Loyaltty owns all interest in and to the App, Customer Data, Loyaltty trade names, logos, trademarks, service marks, domain names, social media identifiers, all data collected through or from the App, all audiovisual content, video recordings, audio recordings, photographs, graphics, artwork, text or any other content created by Loyaltty or at Loyaltty’s direction, or assigned to Loyaltty, and any materials, software, technology or tools used or provided by Loyaltty to promote, sell/resell (as may be applicable) or distribute the Merchant Offering and conduct its business in connection therewith (collectively “Loyaltty IP”). Merchant shall not use, sell, rent, lease, sublicense, distribute, broadcast, transmit, stream, place shift, transfer, copy, reproduce, download, time shift, display, perform, modify or timeshare the Loyaltty IP or any portion thereof, or use such Loyaltty IP as a component of or a base for products or services prepared for commercial use, sale, sublicense, lease, access or distribution, except that Loyaltty grants Merchant a limited, non-exclusive, revocable, non- transferable, non-sub licensable license during the Term to use one copy of Loyaltty’s mobile merchant software application on a single mobile computer, tablet computer, or other device, solely for the purposes permitted by that software, and to make one copy of the software for back-up purposes. Merchant shall keep the Loyaltty IP confidential, and shall not prepare any derivative work based on the Loyaltty IP or translate, reverse engineer, decompile or disassemble the Loyaltty IP. Merchant shall not take any action to challenge or object to the validity of Loyaltty’s rights in the Loyaltty IP or Loyaltty’s ownership or registration thereof. Except as specifically provided in this Agreement, Merchant and any third party assisting Merchant with its obligations in this Agreement, are not authorized to use Loyaltty IP in any medium without prior written approval from an authorized representative of Loyaltty. Merchant shall not include any trade name, trademark, service mark, domain name, social media identifier, of Loyaltty or its affiliates, or any variant or misspelling thereof, in any trademark, domain name, email address, social network identifier, metadata or search engine keyword. Merchant shall not use or display any Loyaltty IP in a manner that could reasonably imply an endorsement, relationship, affiliation with, or sponsorship between Merchant or a third party and Loyaltty. All rights to the Loyaltty IP not expressly granted in this Agreement are reserved by Loyaltty.
            </li>
            <li className='mb-2'>
            If Merchant provides Loyaltty or any of its affiliates with feedback, suggestions, reviews, modifications, data, images, text, or other information or content about a Loyaltty product or service or otherwise in connection with this Agreement, any Loyaltty IP, or Merchant’s participation in the Merchant Offering or Coupon, (collectively, “Feedback”), Merchant irrevocably assigns to Loyaltty all right, title, and interest in and to Feedback. In the event your assignment to Loyaltty is invalid for any reason, you hereby irrevocably grant Loyaltty and its affiliates a perpetual, paid-up, royalty-free, nonexclusive, worldwide, irrevocable, freely transferable right and license to (i) use, reproduce, perform, display, and distribute Feedback; (ii) adapt, modify, re-format, and create derivative works of Feedback for any purpose and sublicense the foregoing rights to any other person or entity. Merchant warrants that: (A) Feedback is Merchant’s original work, or Merchant obtained Feedback in a lawful manner; and (B) Loyaltty and its sublicensees’ exercise of rights under the license above will not violate any person’s or entity’s rights, including any copyright rights. Merchant agrees to provide Loyaltty such assistance as Loyaltty might require to document, perfect, or maintain Loyaltty’s rights in and to Feedback.
            </li>
          </ul>

          <h2 className="text-2xl font-bold mb-4">
          9. Representations and Warranties
            </h2>
            <ul className="list-disc ml-8 mb-4">
              <li className='mb-2'>Merchant has the right, power and authority to enter into this Agreement;</li>
              <li className='mb-2'>Merchant, if required by applicable law, is registered for sales and use tax collection purposes in all jurisdictions where Merchant’s goods and services will be provided;</li>
              <li className='mb-2'>The Coupon, upon being delivered by Loyaltty, will be available immediately for redemption and Merchant will have sufficient goods and/or services available for redemption through the Promotional Value Expiration Date (i.e., a number of goods and/or services sufficient to fulfill its redemption obligations in connection with the applicable Maximum Number of Coupons);</li>
              <li className='mb-2'>The terms and conditions of the Coupon, including any discounts or goods and services offered thereunder do not and will not violate any, local, state, provincial, territorial or federal law, statute, rule, regulation, or order, including but not limited to, any law or regulation governing the use, sale, and distribution of alcohol and any laws governing Coupons, gift cards, coupons, and gift certificates;</li>
              <li className='mb-2'>The Merchant’s redemption of the Coupon will result in the bona fide provision of goods and/or services by Merchant to the purchaser;</li>
              <li className='mb-2'>Merchant owns all interest in and to the Merchant IP and has licensing rights in (with the right to sublicense to Loyaltty) the Third Party IP, and has the right to grant the License stated in this Agreement;</li>
              <li className='mb-2'>The Merchant IP and the Third Party IP, the Merchant Offering, Loyaltty’s use and promotion thereof, and the results of such Merchant Offerings, will not infringe, dilute, misappropriate, or otherwise violate, anywhere in the world, any patent, copyright, logo, trademark, service mark, trade name, rights in designs, or other intellectual property right or right of privacy or publicity of any third party or any applicable law, and does not and will not result from the misappropriation of any trade secret or the breach of any confidentiality obligations to any person or entity;</li>
              <li className='mb-2'>The Merchant IP and Third Party IP does not include any material that is unlawful, threatening, abusive, defamatory, vulgar, obscene, profane or otherwise objectionable, or that encourages conduct that constitutes a criminal offense, gives rise to civil liability or otherwise violates any law;</li>
              <li className='mb-2'>the Coupons and any advertising or promotion of Merchant’s goods and services relating thereto will not constitute false, deceptive or unfair advertising or disparagement under any applicable law;</li>
              <li className='mb-2'>Merchant and its employees, contractors and agents have had the proper education and training and hold all required and up-to-date regulatory authorization, licenses and certifications relating to any Merchant Offering to provide the goods or services described in this Agreement;</li>
              <li className='mb-2'>Merchant’s business information and direct deposit details as provided in this Agreement, indicating where payments should be forwarded are accurate and Merchant is the authorized entity to receive the funds forwarded by Loyaltty;</li>
              <li className='mb-2'>Merchant is not authorized to resell, broker or otherwise disclose any Customer Data (as defined in this Agreement) to any third party, in whole or in part, for any purpose, and Merchant is not authorized to copy or otherwise reproduce any Customer Data other than for the purpose of redeeming or verifying the validity of Coupons in connection with this Agreement .</li>
              <li className='mb-2'>the Merchant Offering is:
free from defects in workmanship, materials and design,
merchantable and suitable for the purposes, if any, stated in the Agreement, and
genuine, bona fide products, as described herein and does not violate the rights of any third party,</li>
              <li className='mb-2'>It shall abide by Loyaltty’s Vendor Code of Conduct, as updated from time to time (currently located at https://www.Loyaltty.com/pages/vendor-code-of-conduct)</li>
              <li className='mb-2'>It shall abide by Loyaltty’s Customer Transparency Policy, as updated from time to time (currently located at https://www.Loyaltty.com/legal/customer-transparency).</li>
              </ul>

              <h2 className="text-2xl font-bold mb-4">
              10. Indemnification
            </h2>
            <p className='mb-2'>To the extent allowed under applicable law, Merchant agrees to defend, indemnify and hold Loyaltty, its affiliated and related entities, and any of its respective officers, directors, agents and employees, harmless from and against any claims, lawsuits, investigations, penalties, damages, losses or expenses (including but not limited to reasonable attorneys’ fees and costs) arising out of or relating to any of the following:</p>
            <ul className="list-disc ml-8 mb-4">
              <li className='mb-2'>Any breach or alleged breach by Merchant of this Agreement, or the representations and warranties made in this Agreement;</li>
              <li className='mb-2'>Any claim for state sales, use, or similar tax obligations of Merchant arising from the sale and redemption of a Coupon;</li>
              <li className='mb-2'>Any claim by any local, state, provincial, territorial or federal governmental entity for unredeemed Coupons or unredeemed cash values of Coupons or any other amounts under any applicable abandoned or unclaimed property or escheat law, including but not limited to any claims for penalties and interest;</li>
              <li className='mb-2'>Any claim arising out of a violation of any law or regulation by Merchant or governing Merchant’s goods and/or services;</li>
              <li className='mb-2'>Any claim arising out of Merchant’s violation of law or regulation governing the use, sale, and distribution of alcohol;</li>
              <li className='mb-2'>Any claim by a purchaser or anyone else arising out of or relating to the goods and services provided by Merchant and/or pick up of the goods and services at the Redemption Site, including but not limited to, any claims for false advertising, product defects, personal injury, death, or property damages;</li>
              <li className='mb-2'>Any claim by a purchaser for the Amount Paid;</li>
              <li className='mb-2'>Any claim arising out of Merchant’s misuse of Customer Data, or any violation of an applicable data privacy or security law; and</li>
              <li className='mb-2'>Any claim arising out of Merchant’s negligence, fraud or willful misconduct. Loyaltty maintains the right to control its own defense and to choose and appoint its own defense counsel, regardless of the presence or absence of a conflict of interest between Loyaltty and Merchant. Merchant’s duty to defend and indemnify Loyaltty includes the duty to pay Loyaltty’s reasonable attorneys’ fees and costs, including any expert fees.</li>
              </ul>
              <h2 className="text-2xl font-bold mb-4">11.Confidentiality</h2>
              <p className='mb-2'>The terms for the Merchant Offering described in this Agreement are confidential, and Merchant agrees not to disclose the terms described in this Agreement to any party (other than to its employees, parent companies, shareholders, lawyers and accountants on a strict need-to-know basis or as required by applicable public records and other law, if Merchant has taken the necessary precautions of the kind generally taken with confidential information to preserve the confidentiality of the information made available to such parties). In the event of a breach, Loyaltty is entitled to injunctive relief and a decree for specific performance, and any other relief allowed under applicable law (including monetary damages if appropriate).</p>

              <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
              <p className='mb-2'>EXCEPT FOR MERCHANT’S INDEMNIFICATION OBLIGATIONS HEREUNDER, IN NO EVENT IS EITHER PARTY LIABLE OR OBLIGATED TO THE OTHER PARTY OR ANY THIRD PARTY FOR ANY LOST PROFITS, LOST BUSINESS, SPECIAL, INCIDENTAL, EXEMPLARY, CONSEQUENTIAL, PUNITIVE, OR INDIRECT DAMAGES REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT OR OTHERWISE, EVEN IF INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGES IN ADVANCE. LOYALTTY’S SOLE AND COMPLETE LIABILITY TO MERCHANT FOR ANY CLAIMS ARISING OUT OF OR RELATING TO THIS AGREEMENT, OR ANY ERRORS, OMISSIONS OR MISPLACEMENTS OF ANY COUPON IS LIMITED TO THE AMOUNT OF FEES RETAINED BY LOYALTTY HEREUNDER FOR THE PRECEDING SIX(6) MONTHS AFTER FINAL CALCULATION AND RECONCILIATION OF ALL REFUNDS.</p>

              <p className='mb-2'>THIS LIMITATION OF LIABILITY APPLIES TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND NOTWITHSTANDING THE FAILURE OF ANY LIMITED REMEDY. IN ADDITION, ANY CLAIM BY OR ON BEHALF OF A MERCHANT IN CONNECTION WITH ANY PAYMENT MADE BY LOYALTTY, INCLUDING, BUT NOT LIMITED TO, CLAIMS ALLEGING THAT A MERCHANT WAS UNDERPAID, MUST BE MADE IN WRITING TO LOYALTTY WITHIN NINETY (90) DAYS FROM THE DATE LOYALTTY REMITS THE PAYMENT AT ISSUE. ALL CLAIMS NOT MADE IN ACCORDANCE WITH THE FOREGOING SHALL BE DEEMED WAIVED, RELEASED AND DISCHARGED BY MERCHANT.</p>
              <h2 className="text-2xl font-bold mb-4">
              13. Dispute Resolution
            </h2>
            <p className='mb-2'>All disputes arising out of, or relating in any way to this Agreement, shall be resolved pursuant to this Section 14 Dispute Resolution.</p>
            <ul className="list-disc ml-8 mb-4">
              <li className='mb-2'><b>Binding Arbitration: </b>
EXCEPT AS SPECIFICALLY STATED HEREIN, ANY DISPUTE OR CLAIM BETWEEN MERCHANT AND LOYALTTY ARISING OUT OF, OR RELATING IN ANY WAY TO, THIS AGREEMENT (“DISPUTES”) SHALL BE RESOLVED EXCLUSIVELY BY FINAL, BINDING ARBITRATION. BY VIRTUE OF THE AGREEMENT IN THIS SECTION 14 TO ARBITRATE, MERCHANT AND LOYALTTY ARE EACH GIVING UP THE RIGHT TO GO TO COURT AND HAVE A DISPUTE HEARD BY A JUDGE OR JURY (EXCEPT AS OTHERWISE SET FORTH IN THIS SECTION 14). The provisions of this Section 14 shall constitute Merchant’s and Loyaltty’s written agreement to arbitrate Disputes under the Federal Arbitration Act. The arbitration will be administered by the American Arbitration Association (“AAA”) and conducted before a single arbitrator pursuant to its applicable rules, including those applicable to Commercial Disputes, available at https://www.adr.org or by calling 800-778- 7879. The arbitrator will apply and be bound by this Agreement, apply applicable law and the facts, and issue a reasoned award. To begin an arbitration proceeding, Merchant or Loyaltty must comply with the limitations provision set forth in Section 13 and submit the Dispute by making a demand for arbitration as detailed at https://www.adr.org. If Merchant demands arbitration, it shall simultaneously send a copy of the completed demand to the following address: C T Corporation System, 208 S. LaSalle Street, Suite 814, Chicago, IL 60604. If Loyaltty demands arbitration, it shall simultaneously send a copy of the completed demand to the Merchant’s address of record. Payment of all filing, administration and arbitrator fees will be governed by the AAA’s rules. Loyaltty will reimburse those fees for Disputes totaling less than $10,000 if Merchant is the prevailing party in such arbitration. Loyaltty will not seek attorneys’ fees and costs in arbitration unless the arbitrator determines that a Merchant Dispute is frivolous. The arbitration will be conducted based upon written submissions unless Merchant requests and/or the arbitrator determines that a telephone or in-person hearing is necessary. If the arbitrator grants the request or determines an in-person hearing is necessary, the hearing will proceed in Chicago, Illinois, unless the arbitrator determines or we agree that the matter should proceed in the county of Merchant’s principal place of business.</li>
              <li className='mb-2'><b>Class Action Waiver: </b>
              WE EACH AGREE THAT WE SHALL BRING ANY DISPUTE AGAINST THE OTHER IN OUR RESPECTIVE INDIVIDUAL CAPACITIES AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, REPRESENTATIVE PROCEEDING OR AS AN ASSOCIATION. IN ADDITION, WE EACH AGREE THAT DISPUTES SHALL BE ARBITRATED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION. THE ARBITRATOR DOES NOT HAVE THE POWER TO VARY THESE PROVISIONS.</li>
              <li className='mb-2'> <b>Choice of Law/No Jury Trial: </b>
              If for any reason a Dispute proceeds in court: (i) Merchant and Loyaltty agree that any such Dispute may only be instituted in a state or federal court in Cook County, Illinois; (ii) Merchant and Loyaltty irrevocably consent and submit to the exclusive personal jurisdiction and venue of such courts for resolution of such Disputes; (iii) Merchant and Loyaltty agree that the Federal Arbitration Act, the AAA rules, applicable federal law and the laws of the State of Illinois, without regard to principles of conflicts of law, will govern this Agreement and any Disputes; and (iv) MERCHANT AND LOYALTTY AGREE TO WAIVE ANY RIGHT TO A TRIAL BY JURY.</li>
              <li className='mb-2'>,<b>Injunctive Relief/Attorneys’ Fees </b>
              Notwithstanding anything to the contrary in this Agreement, either party may bring suit in court seeking an injunction or other equitable relief arising out of or relating to claims that the other party’s conduct may cause the other irreparable injury and/or (ii) individual claims for which applicable law expressly prohibits pre-dispute arbitration agreements, if any, where such law is not preempted by the Federal Arbitration Act.</li>
              <p className='mb-2'>In the event Loyaltty is the prevailing party in any Dispute, subject to any exceptions in this Section 14, Merchant shall pay to Loyaltty all reasonable attorneys’ fees and costs incurred by Loyaltty in connection with any Dispute.</p>
              </ul>

              <h2 className="text-2xl font-bold mb-4">
              14. Other
            </h2>
            <ul className="list-disc ml-8 mb-4">
              <li className='mb-2'>The parties are independent contractors. Nothing in this Agreement is to be construed to create a joint venture, partnership, franchise, or an agency relationship between the parties. Neither party has the authority, without the other party’s prior written approval, to bind or commit the other in any way.</li>
              <li className='mb-2'>This Agreement constitutes the entire agreement between the parties relating to its subject matter and supersedes all prior or contemporaneous oral or written agreements concerning such subject matter.</li>
              <li className='mb-2'>Merchant is not authorized to transfer or assign its rights or obligations under this Agreement, whether by operation of law or otherwise, without Loyaltty’s prior written consent. Any waiver must be in writing and signed by an authorized signatory of Loyaltty. Loyaltty is authorized to transfer or assign this Agreement to a present or future affiliate or pursuant to a merger, consolidation, reorganization or sale of all or substantially all of the assets or business, or by operation of law, without notice to Merchant.</li>
              <li className='mb-2'>If any provision of this Agreement should be held to be invalid or unenforceable, the validity and enforceability of the remaining provisions of this Agreement are not affected.</li>
              <li className='mb-2'>EXCEPT AS EXPRESSLY STATED IN THIS AGREEMENT, NEITHER PARTY MAKES ANY REPRESENTATIONS OR WARRANTIES, EXPRESS NOR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. LOYALTTY DOES NOT WARRANT OR GUARANTEE THAT THE SERVICES OFFERED ON OR THROUGH THE APP WILL BE UNINTERRUPTED OR ERROR-FREE, THAT THE COUPONS ARE ERROR- FREE, OR THAT ANY MERCHANT OFFERING WILL RESULT IN ANY REVENUE OR PROFIT FOR MERCHANT.</li>
              <li className='mb-2'>Password Security. You must safeguard your password for, and supervise use of, Loyaltty’s self-serve platform and tools, including, without limitation, Merchant Center, and all information concerning purchases of the Merchant Offering (together your “Account”). You are solely responsible for maintaining the security of your Account and maintaining settings that reflect your preferences. We will assume that anyone using your Account is you or is authorized by you to do so. You agree that you are solely responsible and liable for any activity that occurs under your Account.</li>
              </ul>
          
    </section>
  );
}

export default TermCondition;